config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :appointments
  resources :donations
  devise_for :vets, path: 'vets', controllers: { registrations: 'vets/registrations',
                                                sessions: 'vets/sessions',
                                                confirmations: 'vets/confirmations',
                                                mailer: 'vets/mailer',
                                                passwords: 'vets/passwords',
                                                shared: 'vets/shared',
                                                unlocks: 'vets/unlocks' }

  resources :pets do
  resources :health_records
end

  devise_for :users, path: 'users', controllers: { registrations: 'users/registrations',
                                                  sessions: 'users/sessions',
                                                  confirmations: 'users/confirmations',
                                                  mailer: 'users/mailer',
                                                  passwords: 'users/passwords',
                                                  shared: 'users/shared',
                                                  unlocks: 'users/unlocks' }

  authenticated :user do
    root 'home#index', as: :authenticated_user_root
  end
  authenticated :vet do
    root 'home#index', as: :authenticated_vet_root
  end

  get 'home/template'
  get 'home/account_type_login'
  get 'home/account_type_register'
  root 'home#index'



  #devise_scope :user do  (??)

end

app/models/pet.rb
class Pet < ApplicationRecord

  mount_uploader :avatar, AvatarUploader
  belongs_to :user
  validates :pet_name, presence: true
  validates :pet_birthdate, presence: true
  validates :animal_species, presence: true
  validates :pet_kind, presence: true
  has_many :appointments, :dependent => :destroy
  has_many :health_records, :dependent => :destroy
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]


  # GET /pets or /pets.json
  def index
    if user_signed_in?
      @pets = current_user.pets
    elsif vet_signed_in?
      pet_ids_set = Set.new
      @pets = []
  
      current_vet.appointments.each do |ap|
        pet_id = ap.pet_id
  
        # Check if the pet_id is not already in the set
        unless pet_ids_set.include?(pet_id)
          # Add pet_id to the set and fetch the corresponding pet
          pet_ids_set.add(pet_id)
          @pets << Pet.find(pet_id)
        end
      end
    end
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy!

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:pet_name, :pet_birthdate, :animal_species, :pet_kind, :user_id,:avatar)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<div class="container">
<%= form_with(model: pet, html: {multipart: true}) do |form| %>
  <% if pet.errors.any? %>
    <div  class="error_message " style="top:13%;">
      <ul>
          <li><%= 'Hatalı Giriş Yaptınız' %></li>
        <p>Please try again</p>
      </ul>
    </div>
  <% end %>

  <div class="form_inputs">

  <div class="pet-avatar">
  <em>PET PHOTO</em> </br>
  <%= form.file_field :avatar ,style:"padding-left: 10px; padding-top:10px;" %>
  </div>

  <div class="form_input">
    <%= form.text_field :pet_name, placeholder:"PET NAME"  %>
  </div>

  <div class="form_input">
    <%= form.date_field :pet_birthdate,placeholder:"PET BIRTH DATE"  %>
  </div>

  <div class="form_input">
    <%= form.text_field :animal_species,placeholder:"PET"  %>
  </div>

  <div class="form_input">
    <%= form.text_field :pet_kind,placeholder:"BREED"  %>
  </div>

  <div>
     <%= form.number_field :user_id, value: current_user.id , type:  :hidden%>
  </div>

  </div>

  <div>
    <%= form.submit class:"submitbutton",
    style:"width: 250px;
    height: 40px;
    border-radius:20px;
    position: absolute;
    top: 60%;
    left: 50%;
    transform: translateX(-50%);"%>
  </div>
<% end %>
</div>

app/views/pets/_pet.html.erb
<div class="container">
    <div id="<%= dom_id(@pet) %>">

    <%= image_tag pet.avatar.url, class: 'petphoto_pet',style: 'width: 180px;
    height: 180px;
    border-radius: 50%;
    border: 2px solid #000;
    position: absolute;
    top: 15%;
    left: 40%;
    transform: translateX(-50%);', alt: 'Pet Image' if pet.avatar? %>

            <p class="petname">
            <%= @pet.pet_name %>
            </p>
          <div id="petinformations" class="pet-info-box">
            <p class="petbirthdate">
            <strong>Birth Date:</strong>
            <%= @pet.pet_birthdate %>
            </p>
            </br>
            <p class="petspecies">
            <strong>Species:</strong>
            <%= @pet.animal_species %>
            </p>
            </br>
            <p class="petkind">
            <strong>Kind:</strong>
            <%= @pet.pet_kind %>
            </p>
          </div>
    </div>
</div>

app/views/pets/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW PET EDIT</title>
</head>

<body>
    <header>
      <div class="container">

      <h1 class="edit_text">Edit Pet</h1>
      <%= render "form", pet: @pet %>

      <div class="back_btn">
        <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"), pet_path(@pet) %>
        </div>

      </div>

</header>
</body>
</html>

app/views/pets/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW PET PROFILE CARDS</title>
    <link rel="stylesheet" href="petprofilecards.css">
</head>

<body>
    <header>
        <div id="pets" class="container">
        
            <h2 class="petstitle">Pets</h2>
            </br></br></br>
            
            <% @pets.each do |pet| %>
              <a class="pet-card-link" href="<%= pet_path(pet) %>">
                <div id="pet-card">
                <% if pet.avatar.present? %>
                 <%= image_tag pet.avatar.url, class: 'petphoto'%>
                <% end %>

                  <p class="nameofpet">
                    <%= pet.pet_name %>
                  </p>
                </div>
              </a>
            <% end %>
    
        </div>

        <% if user_signed_in? %>
        <%= link_to "+", new_pet_path, method: :post, id: "plusbutton", style: "text-decoration:none; color: #000;" %>
        <% end %>

    </header>

</body>

</html>

app/views/pets/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW NEW PET</title>
</head>

<body>
    <header>
    <h1 class="edit_text">New pet</h1>

    <%= render "form", pet: @pet %>

    <div class="back_btn">
      <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"), pets_path %>
    </div>

    </header>
</body>
</html>

app/views/pets/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW PET PROFILE INFO</title>
    <link rel="stylesheet" href="petprofileinfo.css">
</head>
<body>
    <header>
    
    <%= render @pet %>

        <div class="petlinks">
          <% if user_signed_in? %>
          <%= link_to "Edit this pet", edit_pet_path(@pet)%>
          <%end%>
          <%= link_to "Health Records" , pet_health_records_path(@pet) %>
          <%  if vet_signed_in? %>
          <%= link_to "New health record", new_pet_health_record_path(@pet) %>
          <%end%>
        </div>

        <div class="back_btn">
        <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"),pets_path %>
        </div>

        <div class="petbuttons">
        <%= button_to "Delete Pet", @pet, method: :delete  %>
        </div>
</header>
</body>
</html>