config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :appointments
  resources :donations
  devise_for :vets, path: 'vets', controllers: { registrations: 'vets/registrations',
                                                sessions: 'vets/sessions',
                                                confirmations: 'vets/confirmations',
                                                mailer: 'vets/mailer',
                                                passwords: 'vets/passwords',
                                                shared: 'vets/shared',
                                                unlocks: 'vets/unlocks' }

  resources :pets do
  resources :health_records
end

  devise_for :users, path: 'users', controllers: { registrations: 'users/registrations',
                                                  sessions: 'users/sessions',
                                                  confirmations: 'users/confirmations',
                                                  mailer: 'users/mailer',
                                                  passwords: 'users/passwords',
                                                  shared: 'users/shared',
                                                  unlocks: 'users/unlocks' }

  authenticated :user do
    root 'home#index', as: :authenticated_user_root
  end
  authenticated :vet do
    root 'home#index', as: :authenticated_vet_root
  end

  get 'home/template'
  get 'home/account_type_login'
  get 'home/account_type_register'
  root 'home#index'



  #devise_scope :user do  (??)

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def account_type_login
  end

  def account_type_register
  end

  def template
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_template.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>E-PAW TEMPLATE</title>
    <link rel="stylesheet" href="template.css">
</head>
<body>
<nav>
<div class="container clearfix">
    <div id="logo-box">
        <a href="/" class="logo">
            E-Paw
        </a>
    </div>
    <div id="nav-links">
        <ul>
        <li class="nav-item text-uppercase">
            <%= link_to 'HOME PAGE' , root_path, class:"nav-link"%>
            </li>

            <% if user_signed_in? %>

            <li class="nav-item text-uppercase">
                <%= link_to 'PET PROFILE' , pets_path, class:"nav-link"%>
            </li>

            <li class="nav-item text-uppercase">
                <%= link_to 'APPOINTMENT' , appointments_path, class:"nav-link"%>
            </li>

            <li class="nav-item text-uppercase">
                <%= link_to 'DONATE' , donations_path, class:"nav-link"%>
            </li>

            <li class="nav-item text-uppercase">
            <a class="nav-link" href="#" role= "button" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.first_name + " "+current_user.last_name %></a>

              <ul class="dropdown"> 
                <li> <a class="sign_up_dropdown" href="#">
                 <%= link_to 'EDIT PROFILE' , edit_user_registration_path, class:"nav-link"%>
                 </a>
                </li>
                
                <li> <a class="sign_up_dropdown" href="#">
                <%= link_to 'SIGN OUT', destroy_user_session_path, data: { "turbo-method": :delete },class:"nav-link" %> 
                </a>
                </li>
              </ul>
            </li>

            

            <% elsif vet_signed_in? %>

            <li class="nav-item text-uppercase">
                <%= link_to 'PETS' , pets_path, class:"nav-link"%>
            </li>

            <li class="nav-item text-uppercase">
                <%= link_to 'APPOINTMENT' , appointments_path, class:"nav-link"%>
            </li>

            <li class="nav-item text-uppercase">
                <%= link_to 'DONATE' , donations_path, class:"nav-link"%>
            </li>

            <li class="nav-item text-uppercase">
            <a class="nav-link" href="#" role= "button" data-bs-toggle="dropdown" aria-expanded="false"><%= current_vet.first_name + " "+current_vet.last_name %></a>

              <ul class="dropdown"> 
                <li> <a class="sign_up_dropdown" href="#">
                 <%= link_to 'EDIT PROFILE' , edit_vet_registration_path, class:"nav-link"%>
                 </a>
                </li>
                
                <li> 
                <%= link_to 'SIGN OUT', destroy_vet_session_path, data: { "turbo-method": :delete },class:"nav-link" %> 
                </a>
                </li>
              </ul>
            </li>


            <% else %>
            <li class="nav-item text-uppercase">
            <a class="nav-link" href="#" role= "button" data-bs-toggle="dropdown" aria-expanded="false">LOG IN</a>

                <ul class="dropdown"> 
                <li> <a class="sign_up_dropdown" href="#">
                 <%= link_to 'USER' , new_user_session_path, class:"nav-link"%>
                 </a>
                </li>
                
                <li> <a class="sign_up_dropdown" href="#">
                <%= link_to 'VET' , new_vet_session_path, class:"nav-link"%>
                </a>
                </li>
                </ul>
            </li>

            <li class="nav-item text-uppercase">
            <a class="nav-link" href="#" role= "button" data-bs-toggle="dropdown" aria-expanded="false">SIGN UP</a>

                <ul class="dropdown"> 
                <li> <a class="sign_up_dropdown" href="#">
                <%= link_to 'USER' , new_user_registration_path, class:"nav-link"%>
                </a>
                </li>
                
                <li> <a class="sign_up_dropdown" href="#">
                <%= link_to 'VET' , new_vet_registration_path, class:"nav-link"%>
                </a>
                </li>
                </ul>
            </li>
            <% end %>

        </ul>
    </div>
    <div class="container">
            <%= image_tag("epaw-logo.png",
            style:" max-width: 179px;
            max-height: 141px;
            position: fixed;
            bottom: 0;
            left: 0;
            z-index: 2;") %>

            <h4 class="slogan">Hands for Paws</h4>
        </div>
        <div class="circle-s"></div>
        <div class="circle-m"></div>
    
</div>
</nav>
</body>

</html>

app/views/home/account_type_login.html.erb
<h1>Account Type</h1>
<p>Choose your account type:</p>
 
    <%= link_to 'User', new_user_session_path%><br/>
    <%= link_to 'Vet', new_vet_session_path%>

app/views/home/account_type_register.html.erb
<h1>Account Type</h1>
<p>Choose your account type:</p>
 
    <%= link_to 'User', new_user_registration_path%><br/>
    <%= link_to 'Vet', new_vet_registration_path%>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>E-PAW MAIN PAGE</title>
    <link rel="stylesheet" href="mainpage.css">
</head>

<body>
    <header>
        <div class="container">
            <%= image_tag("epaw-logo.png", class: "logoimg",
            style:"max-width: 539px;
            max-height: 425px;
            position: fixed; left: 500px; top: 150px;") %>

            <h1>Hands for Paws
            <%= image_tag("pawpng.png", class: "pawimg", 
            style: "max-width: 50px; max-height: auto; background-color: #FFF6F1;") %>

            </h1>
            <div class="welcome-text">Hi. E-Paw invites you to be a hero for all paws, owned and stray, making their lives easier and more
                joyful, one paw at a time.</div>
        </div>
        <div class="circle-l"></div>
    </header>
</body>

</html>

app/views/home/index_vet.html.erb
<h1>Home index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% if vet_signed_in? %>
    
    <%= link_to 'Edit Profile', edit_vet_registration_path%><br/>
    <%= link_to 'Pets', pets_path%>
    <%= button_to 'Sign Out', destroy_vet_session_path, method: :delete%>

<% else%>

    <%= link_to 'Sign In', home_account_type_login_path%>
    <%= link_to 'Sign Up', home_account_type_register_path%>

<% end %>