config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :appointments
  resources :donations
  devise_for :vets, path: 'vets', controllers: { registrations: 'vets/registrations',
                                                sessions: 'vets/sessions',
                                                confirmations: 'vets/confirmations',
                                                mailer: 'vets/mailer',
                                                passwords: 'vets/passwords',
                                                shared: 'vets/shared',
                                                unlocks: 'vets/unlocks' }

  resources :pets do
  resources :health_records
end

  devise_for :users, path: 'users', controllers: { registrations: 'users/registrations',
                                                  sessions: 'users/sessions',
                                                  confirmations: 'users/confirmations',
                                                  mailer: 'users/mailer',
                                                  passwords: 'users/passwords',
                                                  shared: 'users/shared',
                                                  unlocks: 'users/unlocks' }

  authenticated :user do
    root 'home#index', as: :authenticated_user_root
  end
  authenticated :vet do
    root 'home#index', as: :authenticated_vet_root
  end

  get 'home/template'
  get 'home/account_type_login'
  get 'home/account_type_register'
  root 'home#index'



  #devise_scope :user do  (??)

end

app/models/donation.rb
class Donation < ApplicationRecord
    belongs_to :user, :optional => true
    belongs_to :vet, :optional => true
    validates :donation_amount, numericality: {greater_than: 0}
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!

  # GET /donations or /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1 or /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations or /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to donation_url(@donation), notice: "Donation was successfully created." }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1 or /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to donation_url(@donation), notice: "Donation was successfully updated." }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1 or /donations/1.json
  def destroy
    @donation.destroy!

    respond_to do |format|
      format.html { redirect_to donations_url, notice: "Donation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donation_params
      params.require(:donation).permit(:donation_date, :donation_amount, :user_id, :vet_id)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<div class="container">

<div id="dom_id">
<div class="appointment">

  <p class="value">
  <strong>Donation made by:</strong>
  <% @userid = donation.user_id %>
  <% if (@userid!= nil) %>
  <%= User.find(@userid).first_name %>
  <%= User.find(@userid).last_name %>
  <% else %>
  <% @vetid = donation.vet_id %>
  <%= Vet.find(@vetid).first_name %>
  <%= Vet.find(@vetid).last_name %>
  <% end %>
  <% donation.vet_id %>
  </p>

  <p class="value">
    <strong>Donation amount:</strong>
    <%= donation.donation_amount %>
  </p>

  <p class="value">
    <strong>Donation date:</strong>
    <%= donation.created_at %>
  </p>
  </div>
</div>
</div>

app/views/donations/_form.html.erb
<div class="container">
<%= form_with(model: donation) do |form| %>

  <% if donation.errors.any? %>
    <div class="error_message " style="top: 13%;">
      <ul>
        <% donation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
        <p>Please try again</p>
      </ul>
    </div>
  <% end %>
   
  <div class="form_inputs">

  <div class="form_input">
    <% form.datetime_field :donation_date, placeholder:"DONATION DATE: " %>
  </div>

  <div class="form_input">
    <%= form.number_field :donation_amount, placeholder:"DONATION AMOUNT: " %>
  </div>
  </div>


  <% if user_signed_in? %>
    <div>
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>
  <% elsif vet_signed_in? %>
    <div>
      <%= form.hidden_field :vet_id, value: current_vet.id %>
    </div>
  <% else %>
  <% end %>


  <div>
    <%= form.submit class:"submitbutton",
    style:"width: 300px;
    height: 40px;
    border-radius:20px;
    position: absolute;
    top: 30%;
    left: 50%;
    transform: translateX(-50%);"%>
  </div>

<% end %>
</div>

app/views/donations/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW EDIT DONATION</title>
    <link rel="stylesheet" href="donation.css">
</head>

<body>
    <header>
    <div class="container">

    <%= render "form", donation: @donation %>

    <h1 class="edit_text">Editing donation</h1>

    <p class="show_app">
   <%= link_to "Show this donation", @donation %> 
   </p>
  <div class="back_btn">
   <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"), donations_path %>
  </div>
</div>
</header>
</body>
</html>

app/views/donations/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW DONATIONS</title>
    <link rel="stylesheet" href="donation.css">
</head>
<body>
    <header>
    <div class="container">
       <h1 class="edit_text">Donations</h1>
       <% @totalAmount= 0 %>
<div id="donations">
  <% @donations.each do |donation| %>
    <% @totalAmount += donation.donation_amount %>
    <% render donation %>
    
  <% end %>
  <div id="friends" class="card" style="width: 18rem;">
    <div class="card-body">
      <h2 class="card-title"> Total Donations:</h5>
      <h2 class="card-title"> <%= @totalAmount %></h5>
    </div>  
  </div>
  <br/>
  <p> Recent donations: </p>
  
  <% @donations.each do |donation| %>
     
    <div class="donation_infos">
    <p class="donation_info">
    <strong>Donation amount:</strong>
    <%= donation.donation_amount %>
    </p>
     <p class="donation_info">
     <strong>Donation made by:</strong>
     <% @userid = donation.user_id %>
     <% if (@userid!= nil) %>
     <%= User.find(@userid).first_name %>
     <%= User.find(@userid).last_name %>
  
     <% else %>
     <% @vetid = donation.vet_id %>
     <%= Vet.find(@vetid).first_name %>
     <%= Vet.find(@vetid).last_name %>
     <% end %>
     </div>
     <% donation.vet_id %>
     </p>
     <p class="show_app">
     <% link_to "Show this donation", donation %>
     </p>
  <% end %>
  </div>
<div class="show_app" id="new_app">
<%= link_to "New donation", new_donation_path %>
</div>
<div class="back_btn">
      <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"), root_path %>
</div>
</div>
</header>
</body>
</html>

app/views/donations/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW NEW DONATION</title>
    <link rel="stylesheet" href="donation.css">
</head>

<body>
    <header>
    <div class="container">

    <%= render "form", donation: @donation %>

    <h1 class="edit_text">New donation</h1>

    <div class="back_btn">
          <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"), donations_path%>
    </div>
</div>
</header>
</body>
</html>

app/views/donations/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW SHOW DONATIONS</title>
    <link rel="stylesheet" href="appointment.css">
</head>

<body>
    <header>
    <%= render @donation %>

  <div class="back_btn">
      <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"), donations_path %>
  </div>
  <div class="delete_donation_button">
  <%= button_to "Delete this donation", @donation, method: :delete %>
  </div>

</header>
</body>
</html>