config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :appointments
  resources :donations
  devise_for :vets, path: 'vets', controllers: { registrations: 'vets/registrations',
                                                sessions: 'vets/sessions',
                                                confirmations: 'vets/confirmations',
                                                mailer: 'vets/mailer',
                                                passwords: 'vets/passwords',
                                                shared: 'vets/shared',
                                                unlocks: 'vets/unlocks' }

  resources :pets do
  resources :health_records
end

  devise_for :users, path: 'users', controllers: { registrations: 'users/registrations',
                                                  sessions: 'users/sessions',
                                                  confirmations: 'users/confirmations',
                                                  mailer: 'users/mailer',
                                                  passwords: 'users/passwords',
                                                  shared: 'users/shared',
                                                  unlocks: 'users/unlocks' }

  authenticated :user do
    root 'home#index', as: :authenticated_user_root
  end
  authenticated :vet do
    root 'home#index', as: :authenticated_vet_root
  end

  get 'home/template'
  get 'home/account_type_login'
  get 'home/account_type_register'
  root 'home#index'



  #devise_scope :user do  (??)

end

app/models/health_record.rb
class HealthRecord < ApplicationRecord
  belongs_to :pet
  belongs_to :vet
  validates :health_treatments, presence: true
  validates :health_notes, presence: true
end

app/controllers/health_records_controller.rb
class HealthRecordsController < ApplicationController
  before_action :set_health_record, only: %i[ show edit update destroy ]
  
  # GET /health_records or /health_records.json
  def index
    @pet = Pet.find(params[:pet_id])
    @health_records = @pet.health_records
    
  end

  # GET /health_records/1 or /health_records/1.json
  def show

    @health_record = HealthRecord.find(params[:id])
    @pet = @health_record.pet
    
  end

  # GET /health_records/new
  def new
    @pet = Pet.find(params[:pet_id])
    @health_record = HealthRecord.new(pet_id: @pet.id)
  end

  # GET /health_records/1/edit
  def edit
    @health_record = HealthRecord.find(params[:id])
    @pet = @health_record.pet
     end

  # POST /health_records or /health_records.json
  def create
    @health_record = HealthRecord.new(health_record_params)

    respond_to do |format|
      if @health_record.save
        format.html { redirect_to pet_health_records_url(@health_record), notice: "Health record was successfully created." }
        format.json { render :show, status: :created, location: @health_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @health_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /health_records/1 or /health_records/1.json
  def update
    @health_record = HealthRecord.find(params[:id])
    respond_to do |format|
      if @health_record.update(health_record_params)
        format.html { redirect_to pet_health_record_url(@health_record), notice: "Health record was successfully updated." }
        format.json { render :show, status: :ok, location: @health_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @health_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /health_records/1 or /health_records/1.json
  def destroy
    @pet = Pet.find(params[:pet_id])
    @health_record.destroy

    respond_to do |format|
      format.html { redirect_to pet_health_records_url(@pet), notice: "Health record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health_record
      @health_record = HealthRecord.find(params[:id])
      end

    # Only allow a list of trusted parameters through.
    def health_record_params
      params.require(:health_record).permit(:pet_id, :vet_id, :health_treatments, :health_notes)
    end
end

app/helpers/health_records_helper.rb
module HealthRecordsHelper
end

app/views/health_records/_form.html.erb
<div class="container">
<%= form_with(model: health_record, url: pet_health_records_path) do |form| %>
  <% if health_record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(health_record.errors.count, "error") %> prohibited this health_record from being saved:</h2>

      <ul>
        <% health_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :pet_id, value: @pet.id, class:"input" %>
  </div>

  <div>
    <%= form.hidden_field :vet_id, value: current_vet.id ,class:"input" %>
  </div>

  <div class="form_inputs_healthrecord">

  <div class="form_input">
    <%= form.text_area :health_treatments, placeholder:"Health Treatments"%>
  </div>

  <div class="form_input">
    <%= form.text_area :health_notes, placeholder:"Health Notes" %>
  </div>
  
  </div>

  <div>
    <%= form.submit class:"submitbutton",
    style:"width: 300px;
    height: 40px;
    border-radius:20px;"%>
  </div>
<% end %>
</div>

app/views/health_records/_health_record.html.erb
<div class="container">
<div id="<%= dom_id health_record %>">
<div class="health_record">

  <p class="value">
    <strong>Health treatments:</strong>
    <%= health_record.health_treatments %>
  </p>

  <p class="value">
    <strong>Health notes:</strong>
    <%= health_record.health_notes %>
  </p>

  <p class="value">
  <strong>Vet Name:</strong>
  <%= health_record.vet.first_name %>
</p>

</div>
</div>
</div>

app/views/health_records/edit.html.erb
<%= form_with(model: @health_record, url: pet_health_record_path(@pet, @health_record), method: :patch) do |form| %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW EDIT HEALTH RECORD</title>
</head>

<body>
    <header>
      <div class="container">

      <h1 class="edit_text">Edit Health Record</h1>
      <%= render "form", health_record: @health_record %>

      <div class="back_btn">
        <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"), pet_health_record_path(@pet, @health_record) %>
        </div>

      </div>

</header>
</body>
</html>

<%end%>

app/views/health_records/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW HEALTH RECORD</title>
    <link rel="stylesheet" href="healthrecords.css">
</head>

<body>
    <header>
      <div class="container">

      <h1 class="health_record_text">Health records</h1>

      <div id="health_records">
        <% @health_records.each do |health_record| %>
        <div class="health_record_box">

        <p class="health_info">
          <strong>Health Treatment:</strong>
          <%= health_record.health_treatments %>
        </p>
      
        <div class="show_hr">
          <%= link_to "Show this health record", pet_health_record_path(@pet, health_record) %>
        </div>
    </div>
  <% end %>
</div>

      
      <div class="back_btn">
      <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"), pet_path(@pet) %>
      </div>
 </div>

</header>
</body>
</html>

app/views/health_records/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW NEW HEALTH RECORD</title>
</head>
<body>
    <header>
    <h1 class="edit_text">New Health Record</h1>
    
    <%= render "form", health_record: @health_record %>

    <div class="back_btn">
    <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"), pet_health_records_path %>
    </div>
</header>
</body>
</html>

app/views/health_records/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PAW HEALTH RECORD</title>
    <link rel="stylesheet" href="petprofileinfo.css">
</head>
<body>
    <header>
    
    <%= render @health_record %>

        <% if vet_signed_in? %>
        <div class="petlinks">
        <%= link_to "Edit this health record", edit_pet_health_record_path(@health_record) %> 
        </div>
        <%end%>

        <div class="back_btn">
        <%= link_to image_tag("back-button.png", alt: "Back",style: "width: 50px; height: 50px;"), pet_health_records_path %>
        </div>
        
        <% if vet_signed_in? %>
        <div class="delete_health_record_buttons">
        <%= button_to "Delete this health record",pet_health_record_path(@pet, @health_record), method: :delete %>
        </div>
        <%end%>
</header>
</body>
</html>